#!/bin/bash

number=25

# if [ $((number % 2)) -eq 0 ];
# then
#    echo "The number $number is even!";
# else 
#    echo "The number $number is odd!"
# fi

((number % 2 == 0)) && echo "The number $number is even!" || echo "The number $number is odd!"